/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FormulaMindMapPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/view.ts
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_ROOT_LATEX = "\\text{\u4E2D\u5FC3\u4E3B\u9898}";
function genId() {
  try {
    const c = typeof crypto !== "undefined" ? crypto : null;
    if (c == null ? void 0 : c.randomUUID) return c.randomUUID().slice(0, 8);
  } catch (e) {
  }
  return Math.random().toString(36).slice(2, 10);
}
function emptyData() {
  return {
    version: 1,
    nodes: [{ id: genId(), parent: null, x: 0, y: 0, latex: DEFAULT_ROOT_LATEX }]
  };
}
var DEFAULT_DATA_JSON = JSON.stringify(emptyData());
function serializeData(data) {
  return JSON.stringify(data);
}
function parseData(src) {
  try {
    const raw = JSON.parse(src.trim());
    if (!raw || !Array.isArray(raw.nodes)) return null;
    const seen = /* @__PURE__ */ new Set();
    const nodes = [];
    for (const n of raw.nodes) {
      if (!n || typeof n.id !== "string" || !n.id) continue;
      if (seen.has(n.id)) continue;
      seen.add(n.id);
      nodes.push({
        id: n.id,
        parent: typeof n.parent === "string" && n.parent ? n.parent : null,
        x: Number(n.x) || 0,
        y: Number(n.y) || 0,
        latex: typeof n.latex === "string" ? n.latex : ""
      });
    }
    const ids = new Set(nodes.map((n) => n.id));
    for (const n of nodes) if (n.parent && !ids.has(n.parent)) n.parent = null;
    if (nodes.length === 0) return emptyData();
    return { version: 1, nodes };
  } catch (e) {
    return null;
  }
}
function extractBlock(text) {
  const m = /```fmm[^\S\n]*\n([\s\S]*?)\n?```/.exec(text);
  return m ? m[1] : null;
}
function replaceBlock(text, json) {
  const block = "```fmm\n" + json + "\n```";
  const re = /```fmm[^\S\n]*\n[\s\S]*?\n?```/;
  if (re.test(text)) {
    return text.replace(re, () => block);
  }
  const base = text.trimEnd();
  return (base ? base + "\n\n" : "") + block + "\n";
}
function isDescendant(data, maybeChildId, ancestorId) {
  let cur = data.nodes.find((n) => n.id === maybeChildId);
  const guard = /* @__PURE__ */ new Set();
  while (cur && cur.parent && !guard.has(cur.parent)) {
    guard.add(cur.parent);
    if (cur.parent === ancestorId) return true;
    cur = data.nodes.find((n) => n.id === cur.parent);
  }
  return false;
}
function descendantsOf(data, id) {
  const out = [];
  const stack = [id];
  while (stack.length) {
    const cur = stack.pop();
    for (const n of data.nodes) {
      if (n.parent === cur) {
        out.push(n);
        stack.push(n.id);
      }
    }
  }
  return out;
}

// src/edit-modal.ts
var import_obsidian = require("obsidian");
var FormulaEditModal = class extends import_obsidian.Modal {
  constructor(app, latex, onSubmit) {
    super(app);
    this.latex = latex;
    this.onSubmit = onSubmit;
    this.timer = null;
    // Modal 本身不是 Component，公式渲染需要一个挂载用的 Component
    this.renderComponent = new import_obsidian.Component();
  }
  onOpen() {
    this.titleEl.setText("\u7F16\u8F91\u516C\u5F0F");
    this.contentEl.addClass("fmm-edit-modal");
    const inputWrap = this.contentEl.createDiv("fmm-edit-input");
    this.inputEl = inputWrap.createEl("textarea");
    this.inputEl.value = this.latex;
    this.inputEl.placeholder = "\u4F8B\u5982\uFF1A\\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}";
    const previewWrap = this.contentEl.createDiv("fmm-edit-preview");
    previewWrap.createDiv("fmm-edit-preview-label").setText("\u9884\u89C8");
    this.previewEl = previewWrap.createDiv("fmm-edit-preview-body");
    new import_obsidian.Setting(this.contentEl).addButton((b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close())).addButton((b) => b.setCta().setButtonText("\u4FDD\u5B58").onClick(() => this.save()));
    this.inputEl.addEventListener("input", () => this.updatePreview());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        this.save();
      }
    });
    this.renderComponent.load();
    this.updatePreview();
    this.inputEl.focus();
    const len = this.inputEl.value.length;
    this.inputEl.setSelectionRange(len, len);
  }
  updatePreview() {
    if (this.timer) window.clearTimeout(this.timer);
    this.timer = window.setTimeout(() => {
      this.timer = null;
      this.previewEl.empty();
      const v = this.inputEl.value.trim();
      if (!v) {
        this.previewEl.setText("\uFF08\u7A7A\u516C\u5F0F\uFF09");
        this.previewEl.addClass("fmm-muted");
        return;
      }
      this.previewEl.removeClass("fmm-muted");
      import_obsidian.MarkdownRenderer.render(this.app, "$$" + v + "$$", this.previewEl, "", this.renderComponent).catch(
        () => {
          this.previewEl.setText(v);
        }
      );
    }, 150);
  }
  save() {
    this.onSubmit(this.inputEl.value.trim());
    this.close();
  }
  onClose() {
    if (this.timer) window.clearTimeout(this.timer);
    this.contentEl.empty();
    this.renderComponent.unload();
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, title, message, confirmLabel, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
    this.titleEl.setText(title);
    this.contentEl.createEl("p", { text: message });
    new import_obsidian.Setting(this.contentEl).addButton((b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close())).addButton(
      (b) => b.setWarning().setButtonText(confirmLabel).onClick(() => {
        this.close();
        this.onConfirm();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/view.ts
var VIEW_TYPE_FMM = "formula-mindmap-view";
var FormulaMindMapView = class extends import_obsidian2.ItemView {
  constructor(leaf) {
    super(leaf);
    this.path = "";
    this.data = { version: 1, nodes: [] };
    this.nodeEls = /* @__PURE__ */ new Map();
    this.renderTokens = /* @__PURE__ */ new Map();
    this.scale = 1;
    this.tx = 0;
    this.ty = 0;
    this.gesture = null;
    this.dropTargetId = null;
    this.selectedId = null;
    this.saveTimer = null;
    this.dirty = false;
    this.edgesScheduled = false;
    this.onFileModify = async (file) => {
      if (file.path !== this.path || this.dirty || this.gesture) return;
      const f = this.app.vault.getAbstractFileByPath(this.path);
      if (!(f instanceof import_obsidian2.TFile)) return;
      const text = await this.app.vault.cachedRead(f);
      const block = extractBlock(text);
      const parsed = block ? parseData(block) : null;
      if (!parsed) return;
      if (serializeData(parsed) === serializeData(this.data)) return;
      this.data = parsed;
      this.selectedId = null;
      await this.renderAll();
    };
    // ---------- 交互 ----------
    this.onPointerDown = (e) => {
      if (e.button !== 0) return;
      const target = e.target;
      if (!target || typeof target.closest !== "function") return;
      if (target.closest(".fmm-zoom") || target.closest(".fmm-node-add")) return;
      this.canvasEl.focus({ preventScroll: true });
      const nodeEl = target.closest(".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) {
        const id = nodeEl.dataset.id;
        const node = this.data.nodes.find((n) => n.id === id);
        if (!node) return;
        this.select(id);
        this.gesture = {
          kind: "drag",
          id,
          startClientX: e.clientX,
          startClientY: e.clientY,
          startX: node.x,
          startY: node.y,
          moved: false
        };
      } else {
        this.gesture = {
          kind: "pan",
          startClientX: e.clientX,
          startClientY: e.clientY,
          startTx: this.tx,
          startTy: this.ty,
          moved: false
        };
        this.canvasEl.addClass("fmm-panning");
      }
      try {
        this.canvasEl.setPointerCapture(e.pointerId);
      } catch (err) {
      }
    };
    this.onPointerMove = (e) => {
      const g = this.gesture;
      if (!g) return;
      const dxScreen = e.clientX - g.startClientX;
      const dyScreen = e.clientY - g.startClientY;
      if (!g.moved && Math.abs(dxScreen) + Math.abs(dyScreen) > 3) {
        g.moved = true;
        if (g.kind === "drag") {
          const el = this.nodeEls.get(g.id);
          if (el) {
            el.addClass("fmm-dragging");
            el.style.pointerEvents = "none";
          }
        }
      }
      if (!g.moved) return;
      if (g.kind === "pan") {
        this.tx = g.startTx + dxScreen;
        this.ty = g.startTy + dyScreen;
        this.applyTransform();
      } else {
        const node = this.data.nodes.find((n) => n.id === g.id);
        if (!node) return;
        node.x = g.startX + dxScreen / this.scale;
        node.y = g.startY + dyScreen / this.scale;
        this.positionNode(node);
        this.scheduleEdges();
        this.updateDropTarget(g.id, e);
      }
    };
    this.onPointerUp = (e) => {
      const g = this.gesture;
      this.gesture = null;
      this.canvasEl.removeClass("fmm-panning");
      if (!g) return;
      try {
        this.canvasEl.releasePointerCapture(e.pointerId);
      } catch (err) {
      }
      if (g.kind === "pan") {
        if (!g.moved) this.select(null);
        return;
      }
      const el = this.nodeEls.get(g.id);
      if (el) {
        el.removeClass("fmm-dragging");
        el.style.pointerEvents = "";
      }
      if (g.moved) this.scheduleSave();
      if (this.dropTargetId) {
        const target = this.dropTargetId;
        this.clearDropTarget();
        const node = this.data.nodes.find((n) => n.id === g.id);
        if (node && target !== g.id && !isDescendant(this.data, target, g.id)) {
          if (node.parent !== target) {
            node.parent = target;
            this.updateEdges();
            this.scheduleSave();
            new import_obsidian2.Notice("\u5DF2\u8C03\u6574\u7236\u5B50\u5173\u7CFB");
          }
        }
      } else {
        this.clearDropTarget();
      }
    };
    this.onPointerCancel = () => {
      this.gesture = null;
      this.canvasEl.removeClass("fmm-panning");
      this.clearDropTarget();
    };
    this.onDblClick = (e) => {
      const target = e.target;
      if (!target || typeof target.closest !== "function") return;
      if (target.closest(".fmm-zoom")) return;
      e.preventDefault();
      const nodeEl = target.closest(".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) {
        this.openEditor(nodeEl.dataset.id);
        return;
      }
      const { x, y } = this.screenToWorld(e.clientX, e.clientY);
      const node = { id: genId(), parent: null, x, y, latex: "" };
      this.data.nodes.push(node);
      this.createNodeEl(node);
      this.select(node.id);
      void this.renderLatex(node.id, node.latex);
      this.updateEdges();
      this.scheduleSave();
      this.openEditor(node.id);
    };
    this.onContextMenu = (e) => {
      e.preventDefault();
      const target = e.target;
      if (!target || typeof target.closest !== "function") return;
      const menu = new import_obsidian2.Menu();
      const nodeEl = target.closest(".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) {
        const id = nodeEl.dataset.id;
        menu.addItem(
          (item) => item.setTitle("\u7F16\u8F91\u516C\u5F0F").setIcon("pencil").onClick(() => this.openEditor(id))
        );
        menu.addItem(
          (item) => item.setTitle("\u6DFB\u52A0\u5B50\u8282\u70B9").setIcon("plus").onClick(() => this.addChildNode(id))
        );
        menu.addSeparator();
        menu.addItem(
          (item) => item.setTitle("\u5220\u9664\u8282\u70B9").setIcon("trash-2").onClick(() => this.deleteNode(id))
        );
      } else {
        menu.addItem(
          (item) => item.setTitle("\u65B0\u5EFA\u6839\u8282\u70B9").setIcon("plus").onClick(() => {
            const { x, y } = this.screenToWorld(e.clientX, e.clientY);
            const node = { id: genId(), parent: null, x, y, latex: "" };
            this.data.nodes.push(node);
            this.createNodeEl(node);
            this.select(node.id);
            void this.renderLatex(node.id, node.latex);
            this.updateEdges();
            this.scheduleSave();
            this.openEditor(node.id);
          })
        );
        menu.addItem(
          (item) => item.setTitle("\u9002\u5E94\u89C6\u56FE").setIcon("maximize").onClick(() => this.fitView())
        );
      }
      menu.showAtMouseEvent(e);
    };
    this.onWheel = (e) => {
      e.preventDefault();
      const factor = Math.exp(-e.deltaY * 15e-4);
      this.zoomAt(e.clientX, e.clientY, factor);
    };
    this.onKeyDown = (e) => {
      if ((e.key === "Delete" || e.key === "Backspace") && this.selectedId) {
        e.preventDefault();
        this.deleteNode(this.selectedId);
      } else if (e.key === "Escape") {
        this.select(null);
      } else if (e.key === "Enter" && this.selectedId) {
        e.preventDefault();
        this.openEditor(this.selectedId);
      } else if (e.key === "Tab" && this.selectedId) {
        e.preventDefault();
        this.addChildNode(this.selectedId);
      }
    };
  }
  getViewType() {
    return VIEW_TYPE_FMM;
  }
  getDisplayText() {
    return "\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE";
  }
  getIcon() {
    return "fmm-icon";
  }
  async setState(state, result) {
    if (state && typeof state.path === "string") this.path = state.path;
    await super.setState(state, result);
  }
  getState() {
    return { ...super.getState(), path: this.path };
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("fmm-view-content");
    this.canvasEl = this.contentEl.createDiv("fmm-canvas");
    this.canvasEl.setAttribute("tabindex", "0");
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.classList.add("fmm-edges");
    this.svgEl = svg;
    this.canvasEl.appendChild(this.svgEl);
    this.worldEl = this.canvasEl.createDiv("fmm-world");
    const hint = this.canvasEl.createDiv("fmm-hint");
    hint.setText(
      "\u53CC\u51FB\u7A7A\u767D\uFF1A\u65B0\u5EFA\u8282\u70B9 \xB7 \u53CC\u51FB\u8282\u70B9\uFF1A\u7F16\u8F91\u516C\u5F0F \xB7 Tab\uFF1A\u6DFB\u52A0\u5B50\u8282\u70B9 \xB7 \u53F3\u952E\uFF1A\u66F4\u591A\u64CD\u4F5C \xB7 \u62D6\u5230\u53E6\u4E00\u8282\u70B9\u4E0A\uFF1A\u6539\u53D8\u7236\u5B50\u5173\u7CFB"
    );
    const zoom = this.canvasEl.createDiv("fmm-zoom");
    const btnOut = zoom.createEl("button", { text: "\u2212" });
    btnOut.setAttribute("aria-label", "\u7F29\u5C0F");
    this.zoomLabelEl = zoom.createSpan("fmm-zoom-label");
    this.zoomLabelEl.setText("100%");
    const btnIn = zoom.createEl("button", { text: "+" });
    btnIn.setAttribute("aria-label", "\u653E\u5927");
    const btnFit = zoom.createEl("button", { text: "\u2922" });
    btnFit.setAttribute("aria-label", "\u9002\u5E94\u89C6\u56FE");
    btnOut.addEventListener("click", () => this.zoomBy(1 / 1.2));
    btnIn.addEventListener("click", () => this.zoomBy(1.2));
    btnFit.addEventListener("click", () => this.fitView());
    this.registerDomEvent(this.canvasEl, "pointerdown", this.onPointerDown);
    this.registerDomEvent(this.canvasEl, "pointermove", this.onPointerMove);
    this.registerDomEvent(this.canvasEl, "pointerup", this.onPointerUp);
    this.registerDomEvent(this.canvasEl, "pointercancel", this.onPointerCancel);
    this.registerDomEvent(this.canvasEl, "dblclick", this.onDblClick);
    this.registerDomEvent(this.canvasEl, "contextmenu", this.onContextMenu);
    this.registerDomEvent(this.canvasEl, "wheel", this.onWheel, { passive: false });
    this.registerDomEvent(this.canvasEl, "keydown", this.onKeyDown);
    this.registerEvent(this.app.vault.on("modify", this.onFileModify));
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (oldPath === this.path) this.path = file.path;
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file.path === this.path) {
          new import_obsidian2.Notice("\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE\uFF1A\u7B14\u8BB0\u5DF2\u88AB\u5220\u9664");
          this.leaf.detach();
        }
      })
    );
    await this.loadDataFromNote();
    await this.renderAll();
    requestAnimationFrame(() => this.fitView());
  }
  async onClose() {
    if (this.saveTimer) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    if (this.dirty) {
      try {
        await this.saveNow();
      } catch (e) {
      }
    }
  }
  onResize() {
    this.scheduleEdges();
  }
  // ---------- 数据 ----------
  async loadDataFromNote() {
    const file = this.app.vault.getAbstractFileByPath(this.path);
    if (file instanceof import_obsidian2.TFile) {
      const text = await this.app.vault.cachedRead(file);
      const block = extractBlock(text);
      const parsed = block ? parseData(block) : null;
      this.data = parsed != null ? parsed : emptyData();
    } else {
      this.data = emptyData();
    }
  }
  scheduleSave() {
    this.dirty = true;
    if (this.saveTimer) window.clearTimeout(this.saveTimer);
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      void this.saveNow();
    }, 600);
  }
  async saveNow() {
    this.dirty = false;
    const file = this.app.vault.getAbstractFileByPath(this.path);
    if (!(file instanceof import_obsidian2.TFile)) return;
    const json = serializeData(this.data);
    await this.app.vault.process(file, (text) => replaceBlock(text, json));
  }
  // ---------- 渲染 ----------
  async renderAll() {
    this.worldEl.replaceChildren();
    this.nodeEls.clear();
    const tasks = [];
    for (const node of this.data.nodes) {
      this.createNodeEl(node);
      tasks.push(this.renderLatex(node.id, node.latex));
    }
    await Promise.all(tasks);
    this.updateEdges();
  }
  createNodeEl(node) {
    const el = this.worldEl.createDiv("fmm-node");
    el.dataset.id = node.id;
    el.createDiv("fmm-node-content");
    const addBtn = el.createEl("button", { text: "+" });
    addBtn.addClass("fmm-node-add");
    addBtn.setAttribute("aria-label", "\u6DFB\u52A0\u5B50\u8282\u70B9");
    addBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      if (node.parent === null && !this.data.nodes.find((n) => n.id === node.id)) return;
      this.addChildNode(node.id);
    });
    this.nodeEls.set(node.id, el);
    this.positionNode(node);
    return el;
  }
  async renderLatex(id, latex) {
    var _a;
    const el = this.nodeEls.get(id);
    if (!el) return;
    const token = ((_a = this.renderTokens.get(id)) != null ? _a : 0) + 1;
    this.renderTokens.set(id, token);
    const content = el.querySelector(".fmm-node-content");
    if (!content) return;
    content.empty();
    content.removeClass("fmm-muted");
    content.removeClass("fmm-raw");
    const src = latex.trim();
    if (!src) {
      content.setText("\uFF08\u53CC\u51FB\u8F93\u5165\u516C\u5F0F\uFF09");
      content.addClass("fmm-muted");
      this.scheduleEdges();
      return;
    }
    try {
      await import_obsidian2.MarkdownRenderer.render(this.app, "$$" + src + "$$", content, this.path, this);
    } catch (e) {
      content.setText(src);
      content.addClass("fmm-raw");
    }
    if (this.renderTokens.get(id) !== token) return;
    this.scheduleEdges();
  }
  positionNode(node) {
    const el = this.nodeEls.get(node.id);
    if (!el) return;
    el.style.left = node.x + "px";
    el.style.top = node.y + "px";
  }
  nodeSize(node) {
    const el = this.nodeEls.get(node.id);
    if (el) return { w: el.offsetWidth, h: el.offsetHeight };
    return { w: 120, h: 50 };
  }
  scheduleEdges() {
    if (this.edgesScheduled) return;
    this.edgesScheduled = true;
    requestAnimationFrame(() => {
      this.edgesScheduled = false;
      this.updateEdges();
    });
  }
  updateEdges() {
    const svg = this.svgEl;
    svg.replaceChildren();
    const NS = "http://www.w3.org/2000/svg";
    for (const node of this.data.nodes) {
      if (!node.parent) continue;
      const parent = this.data.nodes.find((n) => n.id === node.parent);
      if (!parent) continue;
      const ps = this.nodeSize(parent);
      const cs = this.nodeSize(node);
      const x1 = parent.x + ps.w / 2;
      const y1 = parent.y + ps.h / 2;
      const x2 = node.x + cs.w / 2;
      const y2 = node.y + cs.h / 2;
      const dx = (x2 - x1) / 2;
      const path = document.createElementNS(NS, "path");
      path.setAttribute("d", `M ${x1} ${y1} C ${x1 + dx} ${y1}, ${x2 - dx} ${y2}, ${x2} ${y2}`);
      if (node.id === this.selectedId || node.parent === this.selectedId) {
        path.classList.add("fmm-edge-selected");
      }
      svg.appendChild(path);
    }
  }
  applyTransform() {
    const t = `translate(${this.tx}px, ${this.ty}px) scale(${this.scale})`;
    this.worldEl.style.transform = t;
    this.svgEl.style.transform = t;
    this.canvasEl.style.backgroundSize = `${24 * this.scale}px ${24 * this.scale}px`;
    this.canvasEl.style.backgroundPosition = `${this.tx}px ${this.ty}px`;
    this.zoomLabelEl.setText(Math.round(this.scale * 100) + "%");
  }
  clearDropTarget() {
    var _a;
    if (this.dropTargetId) {
      (_a = this.nodeEls.get(this.dropTargetId)) == null ? void 0 : _a.removeClass("fmm-drop-target");
    }
    this.dropTargetId = null;
  }
  updateDropTarget(dragId, e) {
    var _a, _b;
    const hit = this.nodeAtClientPoint(e);
    let tid = null;
    if (hit && hit !== dragId && !isDescendant(this.data, hit, dragId)) tid = hit;
    if (tid === this.dropTargetId) return;
    if (this.dropTargetId) (_a = this.nodeEls.get(this.dropTargetId)) == null ? void 0 : _a.removeClass("fmm-drop-target");
    this.dropTargetId = tid;
    if (tid) (_b = this.nodeEls.get(tid)) == null ? void 0 : _b.addClass("fmm-drop-target");
  }
  nodeAtClientPoint(e) {
    var _a;
    const els = document.elementsFromPoint(e.clientX, e.clientY);
    for (const el of els) {
      const nodeEl = (_a = el.closest) == null ? void 0 : _a.call(el, ".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) return nodeEl.dataset.id;
    }
    return null;
  }
  // ---------- 操作 ----------
  select(id) {
    var _a, _b;
    if (this.selectedId === id) return;
    if (this.selectedId) (_a = this.nodeEls.get(this.selectedId)) == null ? void 0 : _a.removeClass("fmm-selected");
    this.selectedId = id;
    if (id) (_b = this.nodeEls.get(id)) == null ? void 0 : _b.addClass("fmm-selected");
    this.updateEdges();
  }
  openEditor(id) {
    const node = this.data.nodes.find((n) => n.id === id);
    if (!node) return;
    new FormulaEditModal(this.app, node.latex, (latex) => {
      node.latex = latex;
      void this.renderLatex(id, latex);
      this.scheduleSave();
    }).open();
  }
  addChildNode(parentId) {
    const parent = this.data.nodes.find((n) => n.id === parentId);
    if (!parent) return;
    const siblingCount = this.data.nodes.filter((n) => n.parent === parentId).length;
    const ps = this.nodeSize(parent);
    const node = {
      id: genId(),
      parent: parentId,
      x: parent.x + ps.w + 90,
      y: parent.y + siblingCount * 70,
      latex: ""
    };
    this.data.nodes.push(node);
    this.createNodeEl(node);
    this.select(node.id);
    void this.renderLatex(node.id, node.latex);
    this.updateEdges();
    this.scheduleSave();
    this.openEditor(node.id);
  }
  deleteNode(id) {
    const node = this.data.nodes.find((n) => n.id === id);
    if (!node) return;
    const victims = [node, ...descendantsOf(this.data, id)];
    new ConfirmModal(
      this.app,
      "\u5220\u9664\u8282\u70B9",
      `\u5C06\u5220\u9664\u8BE5\u8282\u70B9\u53CA\u5176 ${victims.length - 1} \u4E2A\u5B50\u8282\u70B9\uFF0C\u786E\u5B9A\u5417\uFF1F`,
      "\u5220\u9664",
      () => {
        var _a;
        const ids = new Set(victims.map((v) => v.id));
        this.data.nodes = this.data.nodes.filter((n) => !ids.has(n.id));
        for (const vid of ids) {
          (_a = this.nodeEls.get(vid)) == null ? void 0 : _a.remove();
          this.nodeEls.delete(vid);
          this.renderTokens.delete(vid);
        }
        if (this.selectedId && ids.has(this.selectedId)) this.selectedId = null;
        if (this.data.nodes.length === 0) {
          const root = emptyData().nodes[0];
          this.data.nodes.push(root);
          this.createNodeEl(root);
          void this.renderLatex(root.id, root.latex);
        }
        this.updateEdges();
        this.scheduleSave();
      }
    ).open();
  }
  // ---------- 视图变换 ----------
  screenToWorld(clientX, clientY) {
    const rect = this.canvasEl.getBoundingClientRect();
    return {
      x: (clientX - rect.left - this.tx) / this.scale,
      y: (clientY - rect.top - this.ty) / this.scale
    };
  }
  zoomAt(clientX, clientY, factor) {
    const rect = this.canvasEl.getBoundingClientRect();
    const mx = clientX - rect.left;
    const my = clientY - rect.top;
    const newScale = Math.min(3, Math.max(0.2, this.scale * factor));
    if (newScale === this.scale) return;
    const k = newScale / this.scale;
    this.tx = mx - k * (mx - this.tx);
    this.ty = my - k * (my - this.ty);
    this.scale = newScale;
    this.applyTransform();
  }
  zoomBy(factor) {
    const rect = this.canvasEl.getBoundingClientRect();
    this.zoomAt(rect.left + rect.width / 2, rect.top + rect.height / 2, factor);
  }
  fitView() {
    const nodes = this.data.nodes;
    if (!nodes.length) return;
    const rect = this.canvasEl.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return;
    let minX = Infinity;
    let minY = Infinity;
    let maxX = -Infinity;
    let maxY = -Infinity;
    for (const n of nodes) {
      const s = this.nodeSize(n);
      minX = Math.min(minX, n.x);
      minY = Math.min(minY, n.y);
      maxX = Math.max(maxX, n.x + s.w);
      maxY = Math.max(maxY, n.y + s.h);
    }
    const pad = 80;
    const bw = Math.max(maxX - minX, 1);
    const bh = Math.max(maxY - minY, 1);
    const k = Math.min((rect.width - pad) / bw, (rect.height - pad) / bh, 1);
    this.scale = Math.max(0.2, Math.min(1, k));
    this.tx = (rect.width - bw * this.scale) / 2 - minX * this.scale;
    this.ty = (rect.height - bh * this.scale) / 2 - minY * this.scale;
    this.applyTransform();
  }
};

// src/main.ts
var FMM_ICON_ID = "fmm-icon";
var FMM_ICON_SVG = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="5.5" cy="12" r="2.5"/><circle cx="18.5" cy="5.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/><path d="M8 10.8 16 6.4M8 13.2l8 4.4"/></svg>`;
var DEFAULT_NOTE_NAME = "\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE.md";
function blockFromJson(json) {
  return "```fmm\n" + json + "\n```";
}
var FormulaMindMapPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    (0, import_obsidian3.addIcon)(FMM_ICON_ID, FMM_ICON_SVG);
    this.registerView(VIEW_TYPE_FMM, (leaf) => new FormulaMindMapView(leaf));
    this.registerMarkdownCodeBlockProcessor("fmm", (source, el, ctx) => {
      this.renderEmbedHint(el, ctx.sourcePath);
    });
    this.addCommand({
      id: "open-formula-mindmap",
      name: "\u6253\u5F00\u5F53\u524D\u7B14\u8BB0\u7684\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE\uFF08\u65E0\u5219\u521B\u5EFA\uFF09",
      callback: () => {
        void this.openForActiveNote();
      }
    });
    this.addRibbonIcon(FMM_ICON_ID, "\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE", () => {
      void this.openForActiveNote();
    });
  }
  renderEmbedHint(el, sourcePath) {
    el.empty();
    const box = el.createDiv("fmm-embed");
    const icon = box.createSpan("fmm-embed-icon");
    icon.innerHTML = FMM_ICON_SVG;
    const text = box.createDiv("fmm-embed-text");
    text.createDiv("fmm-embed-title").setText("\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE");
    text.createDiv("fmm-embed-desc").setText("\u8282\u70B9\u6570\u636E\u4EE5\u6B64\u4EE3\u7801\u5757\u5F62\u5F0F\u4FDD\u5B58\u5728\u672C\u7B14\u8BB0\u4E2D\u3002");
    const btn = box.createEl("button", { text: "\u6253\u5F00\u7F16\u8F91\u89C6\u56FE" });
    btn.addEventListener("click", () => {
      void this.openViewFor(sourcePath);
    });
  }
  async openForActiveNote() {
    const active = this.app.workspace.getActiveFile();
    let path;
    if (active && active.extension === "md") {
      path = active.path;
    } else {
      path = await this.findOrCreateDefaultNote();
    }
    const file = await this.ensureMapNote(path);
    await this.openViewFor(file.path);
  }
  async findOrCreateDefaultNote() {
    const existing = this.app.vault.getAbstractFileByPath(DEFAULT_NOTE_NAME);
    if (existing instanceof import_obsidian3.TFile) return existing.path;
    try {
      await this.app.vault.create(DEFAULT_NOTE_NAME, blockFromJson(DEFAULT_DATA_JSON));
    } catch (e) {
    }
    return DEFAULT_NOTE_NAME;
  }
  /** 确保笔记中存在 fmm 数据块（没有就追加模板），返回笔记文件 */
  async ensureMapNote(path) {
    let file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian3.TFile)) {
      const idx = path.lastIndexOf("/");
      if (idx > 0) await this.ensureFolder(path.slice(0, idx));
      return await this.app.vault.create(path, blockFromJson(DEFAULT_DATA_JSON));
    }
    const text = await this.app.vault.read(file);
    if (!extractBlock(text)) {
      await this.app.vault.process(file, (t) => replaceBlock(t, DEFAULT_DATA_JSON));
    }
    return file;
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let cur = "";
    for (const part of parts) {
      cur = cur ? `${cur}/${part}` : part;
      try {
        await this.app.vault.createFolder(cur);
      } catch (e) {
      }
    }
  }
  async openViewFor(path) {
    const { workspace } = this.app;
    for (const leaf2 of workspace.getLeavesOfType(VIEW_TYPE_FMM)) {
      const view = leaf2.view;
      if (view instanceof FormulaMindMapView && view.path === path) {
        workspace.revealLeaf(leaf2);
        return;
      }
    }
    const leaf = workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE_FMM, state: { path }, active: true });
    new import_obsidian3.Notice("\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE\u5DF2\u6253\u5F00", 1500);
    workspace.revealLeaf(leaf);
  }
};
