/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  CATEGORY_LABELS: () => CATEGORY_LABELS,
  default: () => FormulaMindMapPlugin,
  parseAIAnswer: () => parseAIAnswer,
  suggestTextWidth: () => suggestTextWidth
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/view.ts
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_ROOT_LATEX = "\\text{\u4E2D\u5FC3\u4E3B\u9898}";
function genId() {
  try {
    const c = typeof crypto !== "undefined" ? crypto : null;
    if (c == null ? void 0 : c.randomUUID) return c.randomUUID().slice(0, 8);
  } catch (e) {
  }
  return Math.random().toString(36).slice(2, 10);
}
function emptyData() {
  return {
    version: 1,
    nodes: [{ id: genId(), parent: null, x: 0, y: 0, latex: DEFAULT_ROOT_LATEX }]
  };
}
var DEFAULT_DATA_JSON = JSON.stringify(emptyData());
function serializeData(data) {
  return JSON.stringify(data, (key, value) => key === "manuallyMoved" ? void 0 : value);
}
function parseData(src) {
  try {
    const raw = JSON.parse(src.trim());
    if (!raw || !Array.isArray(raw.nodes)) return null;
    const seen = /* @__PURE__ */ new Set();
    const nodes = [];
    for (const n of raw.nodes) {
      if (!n || typeof n.id !== "string" || !n.id) continue;
      if (seen.has(n.id)) continue;
      seen.add(n.id);
      const node = {
        id: n.id,
        parent: typeof n.parent === "string" && n.parent ? n.parent : null,
        x: Number(n.x) || 0,
        y: Number(n.y) || 0,
        latex: typeof n.latex === "string" ? n.latex : ""
      };
      if (typeof n.type === "string" && ["formula", "text", "group"].includes(n.type)) {
        node.type = n.type;
      }
      if (typeof n.label === "string" && n.label) node.label = n.label;
      if (typeof n.body === "string" && n.body) node.body = n.body;
      if (typeof n.category === "string" && n.category) node.category = n.category;
      if (n.collapsed === true) node.collapsed = true;
      if (typeof n.w === "number" && Number.isFinite(n.w) && n.w > 0) node.w = Math.round(n.w);
      nodes.push(node);
    }
    const ids = new Set(nodes.map((n) => n.id));
    for (const n of nodes) if (n.parent && !ids.has(n.parent)) n.parent = null;
    if (nodes.length === 0) return emptyData();
    return { version: 1, nodes };
  } catch (e) {
    return null;
  }
}
function extractBlock(text) {
  const m = /```fmm[^\S\n]*\n([\s\S]*?)\n?```/.exec(text);
  return m ? m[1] : null;
}
function replaceBlock(text, json) {
  const block = "```fmm\n" + json + "\n```";
  const re = /```fmm[^\S\n]*\n[\s\S]*?\n?```/;
  if (re.test(text)) {
    return text.replace(re, () => block);
  }
  const base = text.trimEnd();
  return (base ? base + "\n\n" : "") + block + "\n";
}
function isDescendant(data, maybeChildId, ancestorId) {
  let cur = data.nodes.find((n) => n.id === maybeChildId);
  const guard = /* @__PURE__ */ new Set();
  while (cur && cur.parent && !guard.has(cur.parent)) {
    guard.add(cur.parent);
    if (cur.parent === ancestorId) return true;
    cur = data.nodes.find((n) => n.id === cur.parent);
  }
  return false;
}
function descendantsOf(data, id) {
  const out = [];
  const stack = [id];
  while (stack.length) {
    const cur = stack.pop();
    for (const n of data.nodes) {
      if (n.parent === cur) {
        out.push(n);
        stack.push(n.id);
      }
    }
  }
  return out;
}

// src/parser.ts
var CATEGORY_LABELS = {
  proof: "\u8BC1\u660E",
  derivation: "\u63A8\u5BFC",
  example: "\u4F8B\u5B50",
  theorem: "\u5B9A\u7406",
  definition: "\u5B9A\u4E49",
  note: "\u6CE8\u610F",
  code: "\u4EE3\u7801"
};
var KEYWORD_RULES = [
  { cat: "proof", re: /^(?:证明|证[:：]|proof\b|q\.?e\.?d\b)/i },
  { cat: "derivation", re: /^(?:推导|推算|求解|解题|化简|计算过程|计算|derivation|solution\b)/i },
  { cat: "example", re: /^(?:例子|例题|举例|例[\s\d：:.、(（]|example\b|e\.?g\.\s*[:：]?)/i },
  { cat: "theorem", re: /^(?:定理|引理|命题|推论|theorem|lemma|proposition|corollary)/i },
  { cat: "definition", re: /^(?:定义|definition)/i },
  { cat: "note", re: /^(?:注意|提醒|备注|注[:：]|remark|note\b|caution|warning)/i },
  { cat: "code", re: /^(?:代码|code)/i }
];
function normalizeDelimiters(src) {
  return src.replace(/\\\(([\s\S]+?)\\\)/g, (_m, inner) => `$${inner}$`).replace(/\\\[([\s\S]+?)\\\]/g, (_m, inner) => `$$
${inner}
$$`);
}
function scanBlocks(src) {
  const lines = src.split(/\r?\n/);
  const blocks = [];
  let buf = [];
  let mode = "none";
  let gapBefore = false;
  const flushText = () => {
    if (buf.join("").trim()) {
      blocks.push({ kind: "text", text: buf.join("\n").trim(), gapBefore });
      gapBefore = false;
    }
    buf = [];
  };
  for (const line of lines) {
    if (mode === "code") {
      buf.push(line);
      if (line.trim().startsWith("```")) {
        blocks.push({ kind: "code", text: buf.join("\n").trim(), gapBefore });
        gapBefore = false;
        buf = [];
        mode = "none";
      }
      continue;
    }
    if (mode === "math") {
      buf.push(line);
      const joined = buf.join("\n").trim();
      if (line.trim().endsWith("$$") && joined.length > 4) {
        blocks.push({ kind: "math", text: joined, gapBefore });
        gapBefore = false;
        buf = [];
        mode = "none";
      }
      continue;
    }
    const t = line.trim();
    if (t.startsWith("```")) {
      flushText();
      mode = "code";
      buf = [line];
      continue;
    }
    if (t.startsWith("$$")) {
      flushText();
      const inner = t.slice(2, -2).trim();
      if (t.endsWith("$$") && t.length > 4 && inner) {
        blocks.push({ kind: "math", text: t, gapBefore });
        gapBefore = false;
      } else {
        buf = [line];
        mode = "math";
      }
      continue;
    }
    if (/^#{1,6}\s/.test(t)) {
      flushText();
      blocks.push({ kind: "heading", text: t, gapBefore });
      gapBefore = false;
      continue;
    }
    if (!t) {
      flushText();
      gapBefore = true;
      continue;
    }
    buf.push(line);
  }
  flushText();
  if (mode === "math" && buf.join("").trim()) {
    blocks.push({ kind: "math", text: buf.join("\n").trim(), gapBefore });
  }
  if (mode === "code" && buf.join("").trim()) {
    blocks.push({ kind: "code", text: buf.join("\n").trim(), gapBefore });
  }
  return blocks;
}
function cleanForDetect(line) {
  return line.replace(/^#{1,6}\s*/, "").replace(/^\s*(?:[-*+]|\d+[.、)])\s+/, "").replace(/[*_`~>]/g, "").trim();
}
function detectCategory(text) {
  var _a;
  const line = cleanForDetect((_a = text.split(/\r?\n/)[0]) != null ? _a : "");
  if (!line) return null;
  for (const rule of KEYWORD_RULES) {
    if (rule.re.test(line)) return rule.cat;
  }
  return null;
}
function truncate(s, n) {
  var _a;
  const line = ((_a = s.split(/\r?\n/)[0]) != null ? _a : "").trim();
  return line.length > n ? line.slice(0, n) + "\u2026" : line;
}
function mathInner(blockText) {
  let s = blockText.trim();
  if (s.startsWith("$$")) s = s.slice(2);
  if (s.endsWith("$$")) s = s.slice(0, -2);
  return s.trim();
}
function makeGroup(label, cat, parentId) {
  return {
    id: genId(),
    parent: parentId,
    x: 0,
    y: 0,
    latex: "",
    type: "group",
    category: cat,
    label,
    collapsed: true
  };
}
function suggestTextWidth(body) {
  const cleaned = body.replace(/\s+/g, "").replace(/[*#`>\\|]/g, "");
  const sentences = cleaned.split(/[。！？；!?;]/).filter(Boolean);
  let longest = 0;
  for (const s of sentences) longest = Math.max(longest, s.length);
  const width = Math.round(longest * 13.5 + 36);
  return Math.min(560, Math.max(180, width));
}
function makeText(body, parentId, labelMax = 60) {
  const node = {
    id: genId(),
    parent: parentId,
    x: 0,
    y: 0,
    latex: "",
    type: "text",
    label: truncate(body, labelMax),
    body
  };
  if (body.replace(/\s/g, "").length > 24) node.w = suggestTextWidth(body);
  return node;
}
function parseAIAnswer(raw) {
  var _a;
  const src = normalizeDelimiters((raw != null ? raw : "").trim());
  if (!src) return null;
  const blocks = scanBlocks(src);
  let title = "";
  let startIdx = 0;
  if (blocks.length && blocks[0].kind === "heading" && /^#\s/.test(blocks[0].text)) {
    title = blocks[0].text.replace(/^#\s*/, "");
    startIdx = 1;
  } else {
    const firstTextIdx = blocks.findIndex((b) => b.kind === "text");
    if (firstTextIdx >= 0) {
      const b = blocks[firstTextIdx];
      title = truncate(b.text, 40);
      if (!b.text.includes("\n") && b.text.length <= 40) startIdx = firstTextIdx + 1;
    }
  }
  if (!title) title = "AI \u56DE\u7B54";
  const root = {
    id: genId(),
    parent: null,
    x: 0,
    y: 0,
    latex: "",
    type: "text",
    label: title,
    body: title
  };
  const nodes = [root];
  let openGroup = null;
  const closeGroup = () => {
    openGroup = null;
  };
  for (let i = startIdx; i < blocks.length; i++) {
    const b = blocks[i];
    if (b.kind === "heading") {
      const label = b.text.replace(/^#{1,6}\s*/, "");
      const level = ((_a = b.text.match(/^#+/)) != null ? _a : ["#"])[0].length;
      const cat2 = detectCategory(b.text);
      if (cat2) {
        const g = makeGroup(label, cat2, root.id);
        nodes.push(g);
        openGroup = g;
      } else if (level >= 3 && openGroup) {
        nodes.push(makeText(b.text, openGroup.id, 40));
      } else {
        closeGroup();
        nodes.push(makeText(label, root.id, 60));
      }
      continue;
    }
    if (b.kind === "math") {
      const inner = mathInner(b.text);
      if (!inner) continue;
      if (openGroup && !b.gapBefore) {
        nodes.push({ id: genId(), parent: openGroup.id, x: 0, y: 0, latex: inner, type: "formula" });
        continue;
      }
      closeGroup();
      nodes.push({ id: genId(), parent: root.id, x: 0, y: 0, latex: inner, type: "formula" });
      continue;
    }
    if (b.kind === "code") {
      if (openGroup && !b.gapBefore) {
        nodes.push(makeText(b.text, openGroup.id, 20));
        continue;
      }
      closeGroup();
      const g = makeGroup(CATEGORY_LABELS.code, "code", root.id);
      nodes.push(g);
      nodes.push(makeText(b.text, g.id, 20));
      openGroup = g;
      continue;
    }
    const cat = detectCategory(b.text);
    if (cat) {
      const g = makeGroup(truncate(b.text, 30), cat, root.id);
      nodes.push(g);
      nodes.push(makeText(b.text, g.id));
      openGroup = g;
      continue;
    }
    if (openGroup) {
      nodes.push(makeText(b.text, openGroup.id));
      continue;
    }
    nodes.push(makeText(b.text, root.id));
  }
  if (nodes.length === 1) {
    nodes.push(makeText(src, root.id, 80));
  }
  return { rootId: root.id, nodes };
}

// src/import-modal.ts
var import_obsidian = require("obsidian");
var ImportModal = class extends import_obsidian.Modal {
  constructor(app, mode, onSubmit) {
    super(app);
    this.mode = mode;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.titleEl.setText("\u5BFC\u5165 AI \u56DE\u7B54");
    this.contentEl.addClass("fmm-import-modal");
    this.contentEl.createEl("p", { text: "\u628A GPT \u7B49 AI \u7684\u56DE\u7B54\u7C98\u8D34\u5230\u4E0B\u9762\uFF08\u652F\u6301 Markdown \u4E0E LaTeX\uFF09\u3002" }).addClass("fmm-import-hint");
    const ta = this.contentEl.createEl("textarea");
    ta.addClass("fmm-import-textarea");
    ta.placeholder = "\u5728\u6B64\u7C98\u8D34\uFF08Ctrl+V\uFF09\u2026";
    new import_obsidian.Setting(this.contentEl).setName("\u5BFC\u5165\u65B9\u5F0F").setDesc("\u81EA\u52A8\u62C6\u5206\uFF1A\u6838\u5FC3\u516C\u5F0F\u7559\u6210\u8282\u70B9\uFF0C\u63A8\u5BFC/\u8BC1\u660E/\u4F8B\u5B50\u6298\u53E0\u6210\u5F69\u8272\u5206\u7EC4\u6846\u3002\u6574\u6BB5\u5BFC\u5165\uFF1A\u5168\u90E8\u5185\u5BB9\u7B97\u4E00\u6761\u4FE1\u606F\uFF0C\u4E0D\u62C6\u5206\u3002").addDropdown(
      (d) => d.addOption("auto", "\u81EA\u52A8\u62C6\u5206\uFF08\u63A8\u8350\uFF09").addOption("single", "\u6574\u6BB5\u4F5C\u4E3A\u4E00\u4E2A\u8282\u70B9\uFF08\u4E0D\u62C6\u5206\uFF09").setValue(this.mode).onChange((v) => {
        this.mode = v;
      })
    );
    new import_obsidian.Setting(this.contentEl).addButton(
      (b) => b.setButtonText("\u4ECE\u526A\u8D34\u677F\u8BFB\u53D6").onClick(async () => {
        try {
          const t = await navigator.clipboard.readText();
          if (t && t.trim()) {
            ta.value = t;
          } else {
            new import_obsidian.Notice("\u526A\u8D34\u677F\u662F\u7A7A\u7684");
          }
        } catch (e) {
          new import_obsidian.Notice("\u65E0\u6CD5\u8BFB\u53D6\u526A\u8D34\u677F\uFF0C\u8BF7\u624B\u52A8\u7C98\u8D34");
        }
      })
    ).addButton(
      (b) => b.setCta().setButtonText("\u751F\u6210\u601D\u7EF4\u5BFC\u56FE").onClick(() => {
        const v = ta.value.trim();
        if (!v) {
          new import_obsidian.Notice("\u5185\u5BB9\u4E3A\u7A7A");
          return;
        }
        this.close();
        this.onSubmit(v, this.mode);
      })
    );
    ta.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/edit-modal.ts
var import_obsidian2 = require("obsidian");
var FormulaEditModal = class extends import_obsidian2.Modal {
  constructor(app, opts) {
    super(app);
    this.timer = null;
    // Modal 本身不是 Component，渲染需要一个挂载用的 Component
    this.renderComponent = new import_obsidian2.Component();
    this.opts = opts;
  }
  onOpen() {
    var _a;
    this.titleEl.setText((_a = this.opts.title) != null ? _a : this.opts.mode === "latex" ? "\u7F16\u8F91\u516C\u5F0F" : "\u7F16\u8F91\u5185\u5BB9");
    this.contentEl.addClass("fmm-edit-modal");
    const inputWrap = this.contentEl.createDiv("fmm-edit-input");
    this.inputEl = inputWrap.createEl("textarea");
    this.inputEl.value = this.opts.value;
    this.inputEl.placeholder = this.opts.mode === "latex" ? "\u4F8B\u5982\uFF1A\\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}" : "\u652F\u6301 Markdown \u4E0E $\u884C\u5185\u516C\u5F0F$\u2026";
    const previewWrap = this.contentEl.createDiv("fmm-edit-preview");
    previewWrap.createDiv("fmm-edit-preview-label").setText("\u9884\u89C8");
    this.previewEl = previewWrap.createDiv("fmm-edit-preview-body");
    new import_obsidian2.Setting(this.contentEl).addButton((b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close())).addButton((b) => b.setCta().setButtonText("\u4FDD\u5B58").onClick(() => this.save()));
    this.inputEl.addEventListener("input", () => this.updatePreview());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        this.save();
      }
    });
    this.renderComponent.load();
    this.updatePreview();
    this.inputEl.focus();
    const len = this.inputEl.value.length;
    this.inputEl.setSelectionRange(len, len);
  }
  updatePreview() {
    if (this.timer) window.clearTimeout(this.timer);
    this.timer = window.setTimeout(() => {
      this.timer = null;
      this.previewEl.empty();
      const v = this.inputEl.value.trim();
      const md = this.opts.mode === "latex" ? v ? "$$" + v + "$$" : "" : v;
      if (!md) {
        this.previewEl.setText("\uFF08\u7A7A\uFF09");
        this.previewEl.addClass("fmm-muted");
        return;
      }
      this.previewEl.removeClass("fmm-muted");
      import_obsidian2.MarkdownRenderer.render(this.app, md, this.previewEl, "", this.renderComponent).catch(() => {
        this.previewEl.setText(v);
      });
    }, 150);
  }
  save() {
    this.opts.onSubmit(this.inputEl.value.trim());
    this.close();
  }
  onClose() {
    if (this.timer) window.clearTimeout(this.timer);
    this.contentEl.empty();
    this.renderComponent.unload();
  }
};
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, title, message, confirmLabel, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
    this.titleEl.setText(title);
    this.contentEl.createEl("p", { text: message });
    new import_obsidian2.Setting(this.contentEl).addButton((b) => b.setButtonText("\u53D6\u6D88").onClick(() => this.close())).addButton(
      (b) => b.setWarning().setButtonText(confirmLabel).onClick(() => {
        this.close();
        this.onConfirm();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/view.ts
var VIEW_TYPE_FMM = "formula-mindmap-view";
var FormulaMindMapView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.path = "";
    this.data = { version: 1, nodes: [] };
    this.nodeEls = /* @__PURE__ */ new Map();
    this.renderTokens = /* @__PURE__ */ new Map();
    this.scale = 1;
    this.tx = 0;
    this.ty = 0;
    this.gesture = null;
    this.dropTargetId = null;
    this.selectedIds = /* @__PURE__ */ new Set();
    this.primaryId = null;
    this.visibleIds = /* @__PURE__ */ new Set();
    this.saveTimer = null;
    this.dirty = false;
    this.edgesScheduled = false;
    this.onFileModify = async (file) => {
      if (file.path !== this.path || this.dirty || this.gesture) return;
      const f = this.app.vault.getAbstractFileByPath(this.path);
      if (!(f instanceof import_obsidian3.TFile)) return;
      const text = await this.app.vault.cachedRead(f);
      const block = extractBlock(text);
      const parsed = block ? parseData(block) : null;
      if (!parsed) return;
      if (serializeData(parsed) === serializeData(this.data)) return;
      this.data = parsed;
      this.clearSelection();
      await this.renderAll();
    };
    // ---------- 交互 ----------
    this.onPointerDown = (e) => {
      var _a;
      if (e.button !== 0) return;
      const target = e.target;
      if (!target || typeof target.closest !== "function") return;
      if (target.closest(".fmm-zoom")) return;
      this.canvasEl.focus({ preventScroll: true });
      const nodeEl = target.closest(".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) {
        const id = nodeEl.dataset.id;
        const node = this.data.nodes.find((n) => n.id === id);
        if (!node) return;
        if (target.closest(".fmm-node-add")) return;
        if (e.shiftKey || e.ctrlKey || e.metaKey) {
          this.toggleSelect(id);
          return;
        }
        this.selectSingle(id);
        const dragIds = /* @__PURE__ */ new Set([id, ...descendantsOf(this.data, id).map((n) => n.id)]);
        if (this.selectedIds.has(id) && this.selectedIds.size > 1) {
          for (const sid of this.selectedIds) {
            dragIds.add(sid);
            for (const d of descendantsOf(this.data, sid)) dragIds.add(d.id);
          }
        }
        const snapshot = [];
        for (const did of dragIds) {
          const n = this.data.nodes.find((m) => m.id === did);
          if (n) snapshot.push({ id: did, x: n.x, y: n.y });
        }
        if (target.closest(".fmm-node-resize")) {
          this.gesture = {
            kind: "resize",
            id,
            startClientX: e.clientX,
            startW: (_a = node.w) != null ? _a : nodeEl.offsetWidth,
            oldH: nodeEl.offsetHeight
          };
        } else {
          this.gesture = {
            kind: "drag",
            id,
            startClientX: e.clientX,
            startClientY: e.clientY,
            moved: false,
            snapshot
          };
        }
      } else {
        this.gesture = {
          kind: "pan",
          startClientX: e.clientX,
          startClientY: e.clientY,
          startTx: this.tx,
          startTy: this.ty,
          moved: false
        };
        this.canvasEl.addClass("fmm-panning");
      }
      try {
        this.canvasEl.setPointerCapture(e.pointerId);
      } catch (err) {
      }
    };
    this.onPointerMove = (e) => {
      const g = this.gesture;
      if (!g) return;
      const dxScreen = e.clientX - g.startClientX;
      if (g.kind === "resize") {
        const node = this.data.nodes.find((n) => n.id === g.id);
        const el = this.nodeEls.get(g.id);
        if (!node || !el) return;
        const w = Math.round(Math.min(2e3, Math.max(60, g.startW + dxScreen / this.scale)));
        node.w = w;
        el.style.width = w + "px";
        el.style.maxWidth = "none";
        this.scheduleEdges();
        return;
      }
      const dyScreen = e.clientY - g.startClientY;
      if (!g.moved && Math.abs(dxScreen) + Math.abs(dyScreen) > 3) {
        g.moved = true;
        if (g.kind === "drag") {
          const el = this.nodeEls.get(g.id);
          if (el) {
            el.addClass("fmm-dragging");
            el.style.pointerEvents = "none";
          }
        }
      }
      if (!g.moved) return;
      if (g.kind === "pan") {
        this.tx = g.startTx + dxScreen;
        this.ty = g.startTy + dyScreen;
        this.applyTransform();
      } else {
        const dxw = dxScreen / this.scale;
        const dyw = dyScreen / this.scale;
        for (const s of g.snapshot) {
          const n = this.data.nodes.find((m) => m.id === s.id);
          if (!n) continue;
          n.x = s.x + dxw;
          n.y = s.y + dyw;
          this.positionNode(n);
        }
        this.scheduleEdges();
        this.updateDropTarget(g.id, e);
      }
    };
    this.onPointerUp = (e) => {
      const g = this.gesture;
      this.gesture = null;
      this.canvasEl.removeClass("fmm-panning");
      if (!g) return;
      try {
        this.canvasEl.releasePointerCapture(e.pointerId);
      } catch (err) {
      }
      if (g.kind === "pan") {
        if (!g.moved) this.clearSelection();
        return;
      }
      if (g.kind === "resize") {
        const node = this.data.nodes.find((n) => n.id === g.id);
        const el2 = this.nodeEls.get(g.id);
        if (node && el2) {
          this.shiftColumnBelow(g.id, el2.offsetHeight - g.oldH);
          node.manuallyMoved = true;
          this.scheduleSave();
        }
        return;
      }
      const el = this.nodeEls.get(g.id);
      if (el) {
        el.removeClass("fmm-dragging");
        el.style.pointerEvents = "";
      }
      if (g.moved) {
        for (const s of g.snapshot) {
          const n = this.data.nodes.find((m) => m.id === s.id);
          if (n) n.manuallyMoved = true;
        }
        this.scheduleSave();
      }
      if (this.dropTargetId) {
        const target = this.dropTargetId;
        this.clearDropTarget();
        const node = this.data.nodes.find((n) => n.id === g.id);
        if (node && target !== g.id && !isDescendant(this.data, target, g.id)) {
          if (node.parent !== target) {
            node.parent = target;
            this.updateEdges();
            this.scheduleSave();
            new import_obsidian3.Notice("\u5DF2\u8C03\u6574\u7236\u5B50\u5173\u7CFB");
          }
        }
      } else {
        this.clearDropTarget();
      }
    };
    this.onPointerCancel = () => {
      this.gesture = null;
      this.canvasEl.removeClass("fmm-panning");
      this.clearDropTarget();
    };
    this.onDblClick = (e) => {
      var _a, _b;
      const target = e.target;
      if (!target || typeof target.closest !== "function") return;
      if (target.closest(".fmm-zoom")) return;
      e.preventDefault();
      const nodeEl = target.closest(".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) {
        const id = nodeEl.dataset.id;
        const node2 = this.data.nodes.find((n) => n.id === id);
        const type = (_a = node2 == null ? void 0 : node2.type) != null ? _a : "formula";
        const hasChildren = this.data.nodes.some((n) => n.parent === id);
        const hasBody = !!((_b = node2 == null ? void 0 : node2.body) != null ? _b : "").trim();
        if (type === "group" || hasChildren || hasBody) {
          void this.toggleCollapse(id);
          return;
        }
        this.openEditor(id);
        return;
      }
      const { x, y } = this.screenToWorld(e.clientX, e.clientY);
      const node = { id: genId(), parent: null, x, y, latex: "" };
      this.data.nodes.push(node);
      this.createNodeEl(node);
      this.selectSingle(node.id);
      void this.renderNode(node.id);
      this.updateEdges();
      this.scheduleSave();
      this.openEditor(node.id);
    };
    this.onContextMenu = (e) => {
      var _a;
      e.preventDefault();
      const target = e.target;
      if (!target || typeof target.closest !== "function") return;
      const menu = new import_obsidian3.Menu();
      const nodeEl = target.closest(".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) {
        const id = nodeEl.dataset.id;
        const node = this.data.nodes.find((n) => n.id === id);
        const type = (_a = node == null ? void 0 : node.type) != null ? _a : "formula";
        const hasChildren = this.data.nodes.some((n) => n.parent === id);
        menu.addItem(
          (item) => item.setTitle(type === "formula" ? "\u7F16\u8F91\u516C\u5F0F" : "\u7F16\u8F91\u5185\u5BB9").setIcon("pencil").onClick(() => this.openEditor(id))
        );
        if (type === "group" || hasChildren) {
          menu.addItem(
            (item) => item.setTitle((node == null ? void 0 : node.collapsed) ? "\u5C55\u5F00" : "\u6536\u8D77").setIcon((node == null ? void 0 : node.collapsed) ? "chevrons-down-up" : "chevrons-up-down").onClick(() => void this.toggleCollapse(id))
          );
        }
        if (node == null ? void 0 : node.w) {
          menu.addItem(
            (item) => item.setTitle("\u6062\u590D\u81EA\u52A8\u5BBD\u5EA6").setIcon("rotate-ccw").onClick(() => {
              delete node.w;
              const el = this.nodeEls.get(id);
              if (el) {
                el.style.width = "";
                el.style.maxWidth = "";
              }
              this.scheduleEdges();
              this.scheduleSave();
            })
          );
        }
        menu.addItem(
          (item) => item.setTitle("\u6DFB\u52A0\u5B50\u8282\u70B9").setIcon("plus").onClick(() => this.addChildNode(id))
        );
        menu.addSeparator();
        menu.addItem(
          (item) => item.setTitle("\u5220\u9664\u8282\u70B9").setIcon("trash-2").onClick(() => this.deleteNodes([id]))
        );
      } else {
        menu.addItem(
          (item) => item.setTitle("\u5168\u9009\u6240\u6709\u8282\u70B9").setIcon("box-select").onClick(() => this.selectAll())
        );
        menu.addItem(
          (item) => item.setTitle("\u53D6\u6D88\u5168\u9009").setIcon("square").onClick(() => this.clearSelection())
        );
        menu.addSeparator();
        menu.addItem(
          (item) => item.setTitle("\u65B0\u5EFA\u6839\u8282\u70B9").setIcon("plus").onClick(() => {
            const { x, y } = this.screenToWorld(e.clientX, e.clientY);
            const node = { id: genId(), parent: null, x, y, latex: "" };
            this.data.nodes.push(node);
            this.createNodeEl(node);
            this.selectSingle(node.id);
            void this.renderNode(node.id);
            this.updateEdges();
            this.scheduleSave();
            this.openEditor(node.id);
          })
        );
        menu.addItem(
          (item) => item.setTitle("\u9002\u5E94\u89C6\u56FE").setIcon("maximize").onClick(() => this.fitView())
        );
      }
      menu.showAtMouseEvent(e);
    };
    this.onWheel = (e) => {
      e.preventDefault();
      const factor = Math.exp(-e.deltaY * 15e-4);
      this.zoomAt(e.clientX, e.clientY, factor);
    };
    this.onKeyDown = (e) => {
      var _a;
      if ((e.ctrlKey || e.metaKey) && (e.key === "v" || e.key === "V")) {
        e.preventDefault();
        (_a = navigator.clipboard) == null ? void 0 : _a.readText().then((t) => {
          if (t && t.trim()) void this.importAnswer(t, this.plugin.importMode);
          else new import_obsidian3.Notice("\u526A\u8D34\u677F\u662F\u7A7A\u7684");
        }).catch(() => new import_obsidian3.Notice("\u65E0\u6CD5\u8BFB\u53D6\u526A\u8D34\u677F\uFF0C\u8BF7\u7528\u53F3\u4E0B\u89D2\u300C\u5BFC\u5165\u300D\u6309\u94AE\u7C98\u8D34"));
        return;
      }
      if ((e.ctrlKey || e.metaKey) && (e.key === "a" || e.key === "A")) {
        e.preventDefault();
        this.selectAll();
        return;
      }
      if ((e.key === "Delete" || e.key === "Backspace") && this.selectedIds.size > 0) {
        e.preventDefault();
        this.deleteNodes([...this.selectedIds]);
      } else if (e.key === "Escape") {
        this.clearSelection();
      } else if (e.key === "Enter" && this.primaryId && this.selectedIds.size === 1) {
        e.preventDefault();
        this.openEditor(this.primaryId);
      } else if (e.key === "Tab" && this.primaryId) {
        e.preventDefault();
        this.addChildNode(this.primaryId);
      }
    };
  }
  getViewType() {
    return VIEW_TYPE_FMM;
  }
  getDisplayText() {
    return "\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE";
  }
  getIcon() {
    return "fmm-icon";
  }
  async setState(state, result) {
    if (state && typeof state.path === "string") this.path = state.path;
    await super.setState(state, result);
  }
  getState() {
    return { ...super.getState(), path: this.path };
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("fmm-view-content");
    this.canvasEl = this.contentEl.createDiv("fmm-canvas");
    this.canvasEl.setAttribute("tabindex", "0");
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.classList.add("fmm-edges");
    this.svgEl = svg;
    this.canvasEl.appendChild(this.svgEl);
    this.worldEl = this.canvasEl.createDiv("fmm-world");
    const hint = this.canvasEl.createDiv("fmm-hint");
    hint.setText(
      "\u53CC\u51FB\u7A7A\u767D\uFF1A\u65B0\u5EFA\u8282\u70B9 \xB7 \u53CC\u51FB\u8282\u70B9\uFF1A\u7F16\u8F91\u516C\u5F0F \xB7 Tab\uFF1A\u6DFB\u52A0\u5B50\u8282\u70B9 \xB7 \u53F3\u952E\uFF1A\u66F4\u591A\u64CD\u4F5C \xB7 \u62D6\u5230\u53E6\u4E00\u8282\u70B9\u4E0A\uFF1A\u6539\u53D8\u7236\u5B50\u5173\u7CFB"
    );
    const zoom = this.canvasEl.createDiv("fmm-zoom");
    const btnOut = zoom.createEl("button", { text: "\u2212" });
    btnOut.setAttribute("aria-label", "\u7F29\u5C0F");
    this.zoomLabelEl = zoom.createSpan("fmm-zoom-label");
    this.zoomLabelEl.setText("100%");
    const btnIn = zoom.createEl("button", { text: "+" });
    btnIn.setAttribute("aria-label", "\u653E\u5927");
    const btnFit = zoom.createEl("button", { text: "\u2922" });
    btnFit.setAttribute("aria-label", "\u9002\u5E94\u89C6\u56FE");
    const btnImport = zoom.createEl("button", { text: "\u2913 \u5BFC\u5165" });
    btnImport.setAttribute("aria-label", "\u5BFC\u5165 AI \u56DE\u7B54\uFF08\u7C98\u8D34\u540E\u81EA\u52A8\u751F\u6210\u5BFC\u56FE\uFF09");
    btnOut.addEventListener("click", () => this.zoomBy(1 / 1.2));
    btnIn.addEventListener("click", () => this.zoomBy(1.2));
    btnFit.addEventListener("click", () => this.fitView());
    btnImport.addEventListener("click", () => this.openImportModal());
    this.registerDomEvent(this.canvasEl, "pointerdown", this.onPointerDown);
    this.registerDomEvent(this.canvasEl, "pointermove", this.onPointerMove);
    this.registerDomEvent(this.canvasEl, "pointerup", this.onPointerUp);
    this.registerDomEvent(this.canvasEl, "pointercancel", this.onPointerCancel);
    this.registerDomEvent(this.canvasEl, "dblclick", this.onDblClick);
    this.registerDomEvent(this.canvasEl, "contextmenu", this.onContextMenu);
    this.registerDomEvent(this.canvasEl, "wheel", this.onWheel, { passive: false });
    this.registerDomEvent(this.canvasEl, "keydown", this.onKeyDown);
    this.registerEvent(this.app.vault.on("modify", this.onFileModify));
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (oldPath === this.path) this.path = file.path;
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file.path === this.path) {
          new import_obsidian3.Notice("\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE\uFF1A\u7B14\u8BB0\u5DF2\u88AB\u5220\u9664");
          this.leaf.detach();
        }
      })
    );
    await this.loadDataFromNote();
    await this.renderAll();
    requestAnimationFrame(() => this.fitView());
  }
  async onClose() {
    if (this.saveTimer) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    if (this.dirty) {
      try {
        await this.saveNow();
      } catch (e) {
      }
    }
  }
  onResize() {
    this.scheduleEdges();
  }
  // ---------- 数据 ----------
  async loadDataFromNote() {
    const file = this.app.vault.getAbstractFileByPath(this.path);
    if (file instanceof import_obsidian3.TFile) {
      const text = await this.app.vault.cachedRead(file);
      const block = extractBlock(text);
      const parsed = block ? parseData(block) : null;
      this.data = parsed != null ? parsed : emptyData();
    } else {
      this.data = emptyData();
    }
  }
  scheduleSave() {
    this.dirty = true;
    if (this.saveTimer) window.clearTimeout(this.saveTimer);
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      void this.saveNow();
    }, 600);
  }
  async saveNow() {
    this.dirty = false;
    const file = this.app.vault.getAbstractFileByPath(this.path);
    if (!(file instanceof import_obsidian3.TFile)) return;
    const json = serializeData(this.data);
    await this.app.vault.process(file, (text) => replaceBlock(text, json));
  }
  // ---------- 渲染 ----------
  async renderAll() {
    this.worldEl.replaceChildren();
    this.nodeEls.clear();
    const tasks = [];
    for (const node of this.data.nodes) {
      this.createNodeEl(node);
      tasks.push(this.renderNode(node.id));
    }
    await Promise.all(tasks);
    this.applyVisibility();
  }
  ensureCollapseButton(node) {
    const el = this.nodeEls.get(node.id);
    if (!el || el.querySelector(".fmm-node-collapse")) return;
    const col = el.createEl("button", { text: node.collapsed ? "\u25B8" : "\u25BE" });
    col.addClass("fmm-node-collapse");
    col.setAttribute("aria-label", node.collapsed ? "\u5C55\u5F00" : "\u6536\u8D77");
    col.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.toggleCollapse(node.id);
    });
  }
  createNodeEl(node) {
    var _a;
    const el = this.worldEl.createDiv("fmm-node");
    el.dataset.id = node.id;
    const type = (_a = node.type) != null ? _a : "formula";
    el.addClass(
      type === "group" ? "fmm-node-group" : type === "text" ? "fmm-node-text" : "fmm-node-formula"
    );
    if (type === "group" && node.category) el.addClass("fmm-cat-" + node.category);
    if (node.w && node.w > 0) {
      el.style.width = node.w + "px";
      el.style.maxWidth = "none";
    }
    el.createDiv("fmm-node-content");
    if (type === "group") this.ensureCollapseButton(node);
    const grip = el.createDiv("fmm-node-resize");
    grip.setAttribute("aria-label", "\u62D6\u52A8\u8C03\u6574\u8282\u70B9\u5BBD\u5EA6");
    const addBtn = el.createEl("button", { text: "+" });
    addBtn.addClass("fmm-node-add");
    addBtn.setAttribute("aria-label", "\u6DFB\u52A0\u5B50\u8282\u70B9");
    addBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.addChildNode(node.id);
    });
    this.nodeEls.set(node.id, el);
    this.positionNode(node);
    return el;
  }
  async renderNode(id) {
    var _a, _b, _c, _d, _e, _f;
    const el = this.nodeEls.get(id);
    const node = this.data.nodes.find((n) => n.id === id);
    if (!el || !node) return;
    const token = ((_a = this.renderTokens.get(id)) != null ? _a : 0) + 1;
    this.renderTokens.set(id, token);
    const content = el.querySelector(".fmm-node-content");
    if (!content) return;
    content.empty();
    const type = (_b = node.type) != null ? _b : "formula";
    if (type === "group") {
      const title = content.createDiv("fmm-group-title");
      title.setText(node.label || CATEGORY_LABELS[node.category] || "\u5206\u7EC4");
      const childCount = this.data.nodes.filter((n) => n.parent === id).length;
      if (node.collapsed) {
        const paras = childCount || ((_c = node.body) != null ? _c : "").split(/\n{2,}/).filter((s) => s.trim()).length;
        content.createDiv("fmm-group-meta").setText(`${paras} \u6761\u5185\u5BB9 \xB7 \u53CC\u51FB\u5C55\u5F00`);
      } else if (childCount) {
        content.createDiv("fmm-group-meta").setText("\u53CC\u51FB\u6536\u8D77");
      } else {
        const bodyEl = content.createDiv("fmm-group-body");
        const body = ((_d = node.body) != null ? _d : "").trim();
        if (!body) {
          bodyEl.addClass("fmm-muted");
          bodyEl.setText("\uFF08\u7A7A\uFF09");
        } else {
          try {
            await import_obsidian3.MarkdownRenderer.render(this.app, body, bodyEl, this.path, this);
          } catch (e) {
            bodyEl.setText(body);
          }
        }
      }
    } else if (type === "text") {
      const body = ((_f = (_e = node.body) != null ? _e : node.label) != null ? _f : "").trim();
      if (!body) {
        content.setText("\uFF08\u7A7A\uFF09");
        content.addClass("fmm-muted");
      } else {
        try {
          await import_obsidian3.MarkdownRenderer.render(this.app, body, content, this.path, this);
        } catch (e) {
          content.setText(body);
        }
      }
    } else {
      const src = node.latex.trim();
      if (!src) {
        content.setText("\uFF08\u53CC\u51FB\u8F93\u5165\u516C\u5F0F\uFF09");
        content.addClass("fmm-muted");
        this.scheduleEdges();
        return;
      }
      try {
        await import_obsidian3.MarkdownRenderer.render(this.app, "$$" + src + "$$", content, this.path, this);
      } catch (e) {
        content.setText(src);
        content.addClass("fmm-raw");
      }
    }
    if (this.renderTokens.get(id) !== token) return;
    this.scheduleEdges();
  }
  positionNode(node) {
    const el = this.nodeEls.get(node.id);
    if (!el) return;
    el.style.left = node.x + "px";
    el.style.top = node.y + "px";
  }
  nodeSize(node) {
    const el = this.nodeEls.get(node.id);
    if (el) return { w: el.offsetWidth, h: el.offsetHeight };
    return { w: 120, h: 50 };
  }
  scheduleEdges() {
    if (this.edgesScheduled) return;
    this.edgesScheduled = true;
    requestAnimationFrame(() => {
      this.edgesScheduled = false;
      this.updateEdges();
    });
  }
  updateEdges() {
    const svg = this.svgEl;
    svg.replaceChildren();
    const NS = "http://www.w3.org/2000/svg";
    for (const node of this.data.nodes) {
      if (!node.parent) continue;
      if (!this.visibleIds.has(node.id)) continue;
      const parent = this.data.nodes.find((n) => n.id === node.parent);
      if (!parent || !this.visibleIds.has(parent.id)) continue;
      const ps = this.nodeSize(parent);
      const cs = this.nodeSize(node);
      const x1 = parent.x + ps.w / 2;
      const y1 = parent.y + ps.h / 2;
      const x2 = node.x + cs.w / 2;
      const y2 = node.y + cs.h / 2;
      const dx = (x2 - x1) / 2;
      const path = document.createElementNS(NS, "path");
      path.setAttribute("d", `M ${x1} ${y1} C ${x1 + dx} ${y1}, ${x2 - dx} ${y2}, ${x2} ${y2}`);
      if (this.selectedIds.has(node.id) || node.parent && this.selectedIds.has(node.parent)) {
        path.classList.add("fmm-edge-selected");
      }
      svg.appendChild(path);
    }
  }
  applyVisibility() {
    var _a;
    const visible = /* @__PURE__ */ new Set();
    const childrenOf = /* @__PURE__ */ new Map();
    for (const n of this.data.nodes) {
      if (!n.parent) continue;
      const list = (_a = childrenOf.get(n.parent)) != null ? _a : [];
      list.push(n);
      childrenOf.set(n.parent, list);
    }
    const walk = (n) => {
      var _a2;
      visible.add(n.id);
      if (n.collapsed) return;
      for (const child of (_a2 = childrenOf.get(n.id)) != null ? _a2 : []) walk(child);
    };
    for (const n of this.data.nodes) {
      if (!n.parent) walk(n);
    }
    this.visibleIds = visible;
    for (const [id, el] of this.nodeEls) {
      el.style.display = visible.has(id) ? "" : "none";
    }
    this.updateEdges();
  }
  applyTransform() {
    const t = `translate(${this.tx}px, ${this.ty}px) scale(${this.scale})`;
    this.worldEl.style.transform = t;
    this.svgEl.style.transform = t;
    this.canvasEl.style.backgroundSize = `${24 * this.scale}px ${24 * this.scale}px`;
    this.canvasEl.style.backgroundPosition = `${this.tx}px ${this.ty}px`;
    this.zoomLabelEl.setText(Math.round(this.scale * 100) + "%");
  }
  clearDropTarget() {
    var _a;
    if (this.dropTargetId) {
      (_a = this.nodeEls.get(this.dropTargetId)) == null ? void 0 : _a.removeClass("fmm-drop-target");
    }
    this.dropTargetId = null;
  }
  updateDropTarget(dragId, e) {
    var _a, _b;
    const hit = this.nodeAtClientPoint(e);
    let tid = null;
    if (hit && hit !== dragId && !isDescendant(this.data, hit, dragId)) tid = hit;
    if (tid === this.dropTargetId) return;
    if (this.dropTargetId) (_a = this.nodeEls.get(this.dropTargetId)) == null ? void 0 : _a.removeClass("fmm-drop-target");
    this.dropTargetId = tid;
    if (tid) (_b = this.nodeEls.get(tid)) == null ? void 0 : _b.addClass("fmm-drop-target");
  }
  nodeAtClientPoint(e) {
    var _a;
    const els = document.elementsFromPoint(e.clientX, e.clientY);
    for (const el of els) {
      const nodeEl = (_a = el.closest) == null ? void 0 : _a.call(el, ".fmm-node");
      if (nodeEl == null ? void 0 : nodeEl.dataset.id) return nodeEl.dataset.id;
    }
    return null;
  }
  // ---------- 选择 ----------
  selectSingle(id) {
    this.selectedIds.clear();
    if (id) this.selectedIds.add(id);
    this.primaryId = id;
    this.applySelectionStyles();
  }
  toggleSelect(id) {
    if (this.selectedIds.has(id)) {
      this.selectedIds.delete(id);
    } else {
      this.selectedIds.add(id);
      this.primaryId = id;
    }
    this.applySelectionStyles();
  }
  selectAll() {
    var _a, _b;
    this.selectedIds = new Set(this.visibleIds);
    this.primaryId = (_b = (_a = this.data.nodes.find((n) => this.visibleIds.has(n.id))) == null ? void 0 : _a.id) != null ? _b : null;
    this.applySelectionStyles();
  }
  clearSelection() {
    this.selectSingle(null);
  }
  applySelectionStyles() {
    for (const [id, el] of this.nodeEls) {
      if (this.selectedIds.has(id)) el.addClass("fmm-selected");
      else el.removeClass("fmm-selected");
    }
    this.updateEdges();
  }
  // ---------- 操作 ----------
  openEditor(id) {
    var _a, _b;
    const node = this.data.nodes.find((n) => n.id === id);
    if (!node) return;
    const type = (_a = node.type) != null ? _a : "formula";
    new FormulaEditModal(this.app, {
      title: type === "formula" ? "\u7F16\u8F91\u516C\u5F0F" : type === "text" ? "\u7F16\u8F91\u6587\u5B57\u5185\u5BB9" : "\u7F16\u8F91\u5206\u7EC4\u5185\u5BB9",
      mode: type === "formula" ? "latex" : "markdown",
      value: type === "formula" ? node.latex : (_b = node.body) != null ? _b : "",
      onSubmit: (v) => {
        if (type === "formula") {
          node.latex = v;
        } else {
          node.body = v;
          if (v) node.label = v.split(/\r?\n/)[0].slice(0, 60);
        }
        void this.renderNode(id);
        this.scheduleSave();
      }
    }).open();
  }
  addChildNode(parentId) {
    var _a;
    const parent = this.data.nodes.find((n) => n.id === parentId);
    if (!parent) return;
    if (parent.collapsed) {
      parent.collapsed = false;
      const col = (_a = this.nodeEls.get(parentId)) == null ? void 0 : _a.querySelector(".fmm-node-collapse");
      if (col) col.textContent = "\u25BE";
      void this.renderNode(parentId);
    }
    this.ensureCollapseButton(parent);
    const siblingCount = this.data.nodes.filter((n) => n.parent === parentId).length;
    const ps = this.nodeSize(parent);
    const node = {
      id: genId(),
      parent: parentId,
      x: parent.x + ps.w + 90,
      y: parent.y + siblingCount * 70,
      latex: ""
    };
    this.data.nodes.push(node);
    this.createNodeEl(node);
    this.selectSingle(node.id);
    void this.renderNode(node.id);
    this.applyVisibility();
    this.scheduleSave();
    this.openEditor(node.id);
  }
  deleteNodes(ids) {
    const victims = /* @__PURE__ */ new Set();
    for (const id of ids) {
      const node = this.data.nodes.find((n) => n.id === id);
      if (!node) continue;
      victims.add(id);
      for (const d of descendantsOf(this.data, id)) victims.add(d.id);
    }
    if (victims.size === 0) return;
    new ConfirmModal(
      this.app,
      "\u5220\u9664\u8282\u70B9",
      `\u5C06\u5220\u9664 ${victims.size} \u4E2A\u8282\u70B9\uFF0C\u786E\u5B9A\u5417\uFF1F`,
      "\u5220\u9664",
      () => {
        var _a;
        this.data.nodes = this.data.nodes.filter((n) => !victims.has(n.id));
        for (const vid of victims) {
          (_a = this.nodeEls.get(vid)) == null ? void 0 : _a.remove();
          this.nodeEls.delete(vid);
          this.renderTokens.delete(vid);
        }
        this.clearSelection();
        if (this.data.nodes.length === 0) {
          const root = emptyData().nodes[0];
          this.data.nodes.push(root);
          this.createNodeEl(root);
          void this.renderNode(root.id);
        }
        this.applyVisibility();
        this.scheduleSave();
      }
    ).open();
  }
  // ---------- 导入与分组 ----------
  openImportModal() {
    new ImportModal(this.app, this.plugin.importMode, (text, mode) => {
      if (mode !== this.plugin.importMode) void this.plugin.setImportMode(mode);
      void this.importAnswer(text, mode);
    }).open();
  }
  async toggleCollapse(id) {
    var _a;
    const node = this.data.nodes.find((n) => n.id === id);
    const el = this.nodeEls.get(id);
    if (!node || !el) return;
    const type = (_a = node.type) != null ? _a : "formula";
    const hasChildren = this.data.nodes.some((n) => n.parent === id);
    if (type !== "group" && !hasChildren) return;
    const before = node.collapsed ? el.offsetHeight : this.subtreeHeight(node);
    node.collapsed = !node.collapsed;
    const col = el.querySelector(".fmm-node-collapse");
    if (col) {
      col.textContent = node.collapsed ? "\u25B8" : "\u25BE";
      col.setAttribute("aria-label", node.collapsed ? "\u5C55\u5F00" : "\u6536\u8D77");
    }
    await this.renderNode(id);
    this.applyVisibility();
    const after = node.collapsed ? el.offsetHeight : this.subtreeHeight(node);
    this.shiftColumnBelow(id, after - before);
    this.scheduleSave();
  }
  /** 节点及其可见子树占据的高度（从节点顶部到子树最底端） */
  subtreeHeight(node) {
    let bottom = node.y + this.nodeSize(node).h;
    for (const n of this.data.nodes) {
      if (!this.visibleIds.has(n.id)) continue;
      if (!isDescendant(this.data, n.id, node.id)) continue;
      bottom = Math.max(bottom, n.y + this.nodeSize(n).h);
    }
    return bottom - node.y;
  }
  /** 节点高度变化（折叠/展开、调宽换行）后，把同列下方未手动挪过的可见节点顺移 */
  shiftColumnBelow(anchorId, delta) {
    if (!delta) return;
    const anchor = this.data.nodes.find((n) => n.id === anchorId);
    if (!anchor) return;
    for (const n of this.data.nodes) {
      if (n.id === anchorId || n.manuallyMoved) continue;
      if (!this.visibleIds.has(n.id)) continue;
      if (Math.abs(n.x - anchor.x) > 2) continue;
      if (n.y <= anchor.y) continue;
      n.y += delta;
      this.positionNode(n);
    }
  }
  async importAnswer(text, mode = "auto") {
    var _a, _b;
    const trimmed = (text != null ? text : "").trim();
    if (!trimmed) {
      new import_obsidian3.Notice("\u5185\u5BB9\u4E3A\u7A7A");
      return;
    }
    if (this.data.nodes.length === 1 && this.data.nodes[0].latex === DEFAULT_ROOT_LATEX && !this.data.nodes[0].manuallyMoved) {
      const old = this.data.nodes[0];
      (_a = this.nodeEls.get(old.id)) == null ? void 0 : _a.remove();
      this.nodeEls.delete(old.id);
      this.renderTokens.delete(old.id);
      this.data.nodes = [];
    }
    let baseX = 0;
    if (this.data.nodes.length > 0) {
      let maxX = -Infinity;
      for (const n of this.data.nodes) {
        const s = this.nodeSize(n);
        maxX = Math.max(maxX, n.x + s.w);
      }
      baseX = maxX + 240;
    }
    if (mode === "single") {
      const node = {
        id: genId(),
        parent: null,
        x: baseX,
        y: 0,
        latex: "",
        type: "text",
        label: trimmed.split(/\r?\n/)[0].slice(0, 50),
        body: trimmed,
        w: 520
      };
      this.data.nodes.push(node);
      this.createNodeEl(node);
      await this.renderNode(node.id);
      this.selectSingle(node.id);
      this.updateEdges();
      this.scheduleSave();
      this.fitView();
      new import_obsidian3.Notice("\u5DF2\u4F5C\u4E3A\u5355\u4E2A\u8282\u70B9\u5BFC\u5165");
      return;
    }
    const parsed = parseAIAnswer(trimmed);
    if (!parsed) {
      new import_obsidian3.Notice("\u6CA1\u6709\u89E3\u6790\u51FA\u5185\u5BB9");
      return;
    }
    const root = parsed.nodes[0];
    const children = parsed.nodes.slice(1);
    this.data.nodes.push(...parsed.nodes);
    const tasks = [];
    for (const n of parsed.nodes) {
      this.createNodeEl(n);
      tasks.push(this.renderNode(n.id));
    }
    await Promise.all(tasks);
    const rootEl = this.nodeEls.get(root.id);
    root.x = baseX;
    root.y = 0;
    this.positionNode(root);
    const level1X = baseX + ((_b = rootEl == null ? void 0 : rootEl.offsetWidth) != null ? _b : 140) + 90;
    const level1 = children.filter((n) => n.parent === root.id);
    let cursor = 0;
    for (const n of level1) {
      const el = this.nodeEls.get(n.id);
      if (!el) continue;
      n.x = level1X;
      n.y = cursor;
      this.positionNode(n);
      cursor += el.offsetHeight + 28;
    }
    for (const n of parsed.nodes) {
      if (n.id === root.id) continue;
      const kids = children.filter((c) => c.parent === n.id);
      if (!kids.length) continue;
      const el = this.nodeEls.get(n.id);
      if (!el) continue;
      const kidX = n.x + el.offsetWidth + 90;
      let cy = n.y;
      for (const k of kids) {
        const ke = this.nodeEls.get(k.id);
        if (!ke) continue;
        k.x = kidX;
        k.y = cy;
        this.positionNode(k);
        cy += ke.offsetHeight + 24;
      }
    }
    this.applyVisibility();
    this.selectSingle(root.id);
    this.scheduleSave();
    this.fitView();
    new import_obsidian3.Notice(`\u5DF2\u5BFC\u5165 ${children.length} \u4E2A\u8282\u70B9`);
  }
  // ---------- 视图变换 ----------
  screenToWorld(clientX, clientY) {
    const rect = this.canvasEl.getBoundingClientRect();
    return {
      x: (clientX - rect.left - this.tx) / this.scale,
      y: (clientY - rect.top - this.ty) / this.scale
    };
  }
  zoomAt(clientX, clientY, factor) {
    const rect = this.canvasEl.getBoundingClientRect();
    const mx = clientX - rect.left;
    const my = clientY - rect.top;
    const newScale = Math.min(3, Math.max(0.2, this.scale * factor));
    if (newScale === this.scale) return;
    const k = newScale / this.scale;
    this.tx = mx - k * (mx - this.tx);
    this.ty = my - k * (my - this.ty);
    this.scale = newScale;
    this.applyTransform();
  }
  zoomBy(factor) {
    const rect = this.canvasEl.getBoundingClientRect();
    this.zoomAt(rect.left + rect.width / 2, rect.top + rect.height / 2, factor);
  }
  fitView() {
    const nodes = this.data.nodes;
    if (!nodes.length) return;
    const rect = this.canvasEl.getBoundingClientRect();
    if (rect.width === 0 || rect.height === 0) return;
    let minX = Infinity;
    let minY = Infinity;
    let maxX = -Infinity;
    let maxY = -Infinity;
    for (const n of nodes) {
      if (!this.visibleIds.has(n.id)) continue;
      const s = this.nodeSize(n);
      minX = Math.min(minX, n.x);
      minY = Math.min(minY, n.y);
      maxX = Math.max(maxX, n.x + s.w);
      maxY = Math.max(maxY, n.y + s.h);
    }
    const pad = 80;
    const bw = Math.max(maxX - minX, 1);
    const bh = Math.max(maxY - minY, 1);
    const k = Math.min((rect.width - pad) / bw, (rect.height - pad) / bh, 1);
    this.scale = Math.max(0.2, Math.min(1, k));
    this.tx = (rect.width - bw * this.scale) / 2 - minX * this.scale;
    this.ty = (rect.height - bh * this.scale) / 2 - minY * this.scale;
    this.applyTransform();
  }
};

// src/main.ts
var FMM_ICON_ID = "fmm-icon";
var FMM_ICON_SVG = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="5.5" cy="12" r="2.5"/><circle cx="18.5" cy="5.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/><path d="M8 10.8 16 6.4M8 13.2l8 4.4"/></svg>`;
var DEFAULT_NOTE_NAME = "\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE.md";
function blockFromJson(json) {
  return "```fmm\n" + json + "\n```";
}
var FormulaMindMapPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    /** 上次使用的导入方式，存在 data.json 里，跨重启记忆 */
    this.importMode = "auto";
  }
  async onload() {
    const saved = await this.loadData();
    if (saved && saved.importMode === "single") this.importMode = "single";
    (0, import_obsidian4.addIcon)(FMM_ICON_ID, FMM_ICON_SVG);
    this.registerView(VIEW_TYPE_FMM, (leaf) => new FormulaMindMapView(leaf, this));
    this.registerMarkdownCodeBlockProcessor("fmm", (source, el, ctx) => {
      this.renderEmbedHint(el, ctx.sourcePath);
    });
    this.addCommand({
      id: "open-formula-mindmap",
      name: "\u6253\u5F00\u5F53\u524D\u7B14\u8BB0\u7684\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE\uFF08\u65E0\u5219\u521B\u5EFA\uFF09",
      callback: () => {
        void this.openForActiveNote();
      }
    });
    this.addCommand({
      id: "import-ai-answer",
      name: "\u628A AI \u56DE\u7B54\u5BFC\u5165\u5F53\u524D\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE",
      callback: () => {
        const view = this.app.workspace.getActiveViewOfType(FormulaMindMapView);
        if (!view) {
          new import_obsidian4.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u5F20\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE");
          return;
        }
        view.openImportModal();
      }
    });
    this.addRibbonIcon(FMM_ICON_ID, "\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE", () => {
      void this.openForActiveNote();
    });
  }
  async setImportMode(mode) {
    this.importMode = mode;
    await this.saveData({ importMode: mode });
  }
  renderEmbedHint(el, sourcePath) {
    el.empty();
    const box = el.createDiv("fmm-embed");
    const icon = box.createSpan("fmm-embed-icon");
    icon.innerHTML = FMM_ICON_SVG;
    const text = box.createDiv("fmm-embed-text");
    text.createDiv("fmm-embed-title").setText("\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE");
    text.createDiv("fmm-embed-desc").setText("\u8282\u70B9\u6570\u636E\u4EE5\u6B64\u4EE3\u7801\u5757\u5F62\u5F0F\u4FDD\u5B58\u5728\u672C\u7B14\u8BB0\u4E2D\u3002");
    const btn = box.createEl("button", { text: "\u6253\u5F00\u7F16\u8F91\u89C6\u56FE" });
    btn.addEventListener("click", () => {
      void this.openViewFor(sourcePath);
    });
  }
  async openForActiveNote() {
    const active = this.app.workspace.getActiveFile();
    let path;
    if (active && active.extension === "md") {
      path = active.path;
    } else {
      path = await this.findOrCreateDefaultNote();
    }
    const file = await this.ensureMapNote(path);
    await this.openViewFor(file.path);
  }
  async findOrCreateDefaultNote() {
    const existing = this.app.vault.getAbstractFileByPath(DEFAULT_NOTE_NAME);
    if (existing instanceof import_obsidian4.TFile) return existing.path;
    try {
      await this.app.vault.create(DEFAULT_NOTE_NAME, blockFromJson(DEFAULT_DATA_JSON));
    } catch (e) {
    }
    return DEFAULT_NOTE_NAME;
  }
  /** 确保笔记中存在 fmm 数据块（没有就追加模板），返回笔记文件 */
  async ensureMapNote(path) {
    let file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian4.TFile)) {
      const idx = path.lastIndexOf("/");
      if (idx > 0) await this.ensureFolder(path.slice(0, idx));
      return await this.app.vault.create(path, blockFromJson(DEFAULT_DATA_JSON));
    }
    const text = await this.app.vault.read(file);
    if (!extractBlock(text)) {
      await this.app.vault.process(file, (t) => replaceBlock(t, DEFAULT_DATA_JSON));
    }
    return file;
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let cur = "";
    for (const part of parts) {
      cur = cur ? `${cur}/${part}` : part;
      try {
        await this.app.vault.createFolder(cur);
      } catch (e) {
      }
    }
  }
  async openViewFor(path) {
    const { workspace } = this.app;
    for (const leaf2 of workspace.getLeavesOfType(VIEW_TYPE_FMM)) {
      const view = leaf2.view;
      if (view instanceof FormulaMindMapView && view.path === path) {
        workspace.revealLeaf(leaf2);
        return;
      }
    }
    const leaf = workspace.getLeaf(true);
    await leaf.setViewState({ type: VIEW_TYPE_FMM, state: { path }, active: true });
    new import_obsidian4.Notice("\u516C\u5F0F\u601D\u7EF4\u5BFC\u56FE\u5DF2\u6253\u5F00", 1500);
    workspace.revealLeaf(leaf);
  }
};
